### ISSUE TITLE
 dimension value error

### ISSUE THREAD

**Issue by charles1024** [kavorite/e6tag#1]
Using the latest tensorflow version available (2.7.0) via pip3, the scripts train, eval, and test, all result in the error:

2021-12-16 21:53:37.592253: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (100)
Epoch 1/4
Traceback (most recent call last):
  File "./train.py", line 289, in <module>
    model.fit(**train_config)
  File "/home/charles/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/charles/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    File "/home/charles/.local/lib/python3.8/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/home/charles/.local/lib/python3.8/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/charles/.local/lib/python3.8/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/home/charles/.local/lib/python3.8/site-packages/keras/engine/training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "/home/charles/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "<string>", line 3, in raise_from

    TypeError: Exception encountered when calling layer "model_1" (type Functional).

    Dimension value must be integer or None or have an __index__ method, got value '<attribute 'shape' of 'numpy.generic' objects>' with type '<class 'getset_descriptor'>'

    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 224, 224, 3), dtype=float32)
      • training=True
      • mask=None

I have also tried tensorflow version 2.5.0, but it has a symbol error in one of the shared libraries.

**Comment by kavorite** [comment]
Hey! Thanks for your interest in this repository. At first glance my hunch is that I was debugging at some point and passed an image tensor's `.shape` property instead of the image itself. But that's really just a comment on how poorly maintained this repo is; most of my created GH repos are barely more than stubs and somewhat poorly maintained with next to no integration or unit testing. This is just a testament to that. I do have a working implementation of what this repository was trying to do, it's just in a Colaboratory notebook instead of under proper version control >->. My solution eventually diverged so far from my original vision in this repository that I couldn't bring myself to update it so now it's effectively unmaintained. If interested in how I eventually closed out this project Discord as `flenser#5287`. Going to archive this code. Can't wait to hear from you!
